### ISSUE TITLE
Exact environment to run in

### ISSUE THREAD

**Issue by jbremmer** [axefrog/epicycle#1]
What sort of environment this suppose to work in?

Tried to run under Node@4.2.2. After many problems with dependencies finally blocked on

`Cannot read property 'model' of undefined`

no stack or anything to diagnose.

**Comment by axefrog** [comment]
I'm running on node 5.4.1; could you try with that and see if it makes a difference? I have the whole project running without issues. The stack trace is being omitted inside of Motorcycle. If you open node_modules/@motorcycle/core/lib/index.js, look around line 32 and replace it with:

``` js
var logErrorToConsole = function logErrorToConsole(e) {
  if (console && console.error) {
    console.error('UNCAUGHT ERROR:', e.message || e);
    if(e.stack) {
      console.error(e.stack);
    }
  }
};
```

I believe @TylorS has a fix coming for that, but for now, manually patching it will help you see what's actually happening.

**Comment by jbremmer** [comment]
Node version bump helped, this is working now. Thank you.

One thing to understand though, why would server code run off dist rather than straight from original source?

**Comment by axefrog** [comment]
Glad that worked! The reason for running out of dist is because we're using Babel for transpilation, which means we get to use features not yet available in node.js' version of V8. It also made sense to me that all distributables are built into a single root destination folder so that it can be deleted and recreated easily.
